import smtplib, ssl
port = 587  # For SSL
smtp_server = "mail.redtone.com"
sender_email = "frim@biz.redtone.com"  # Enter your address
password = '6elk@hkU'
theme = "FRIM Notification"
sender = "noreply_frim@redtone.com"

receiver_email = 'ainur.fadzil@redtone.com'  # Enter receiver address

message = """Hi <PegawaiName>, \r\n\
    
Pembalak request to Add Tual.
For detail, please click here <link>\r\n\

This email is automatically generated by system. Please do not reply."""
    
sender_password = password
session = smtplib.SMTP(smtp_server, port)
session.login(sender_email, sender_password)
msg = f'From: {sender}\r\nTo: {receiver_email}\r\nContent-Type: text/plain; charset="utf-8"\r\nSubject: {theme}\r\n\r\n'
msg += message
session.sendmail(sender_email, receiver_email, msg.encode('utf8'))
session.quit()