import smtplib, ssl
import models, settings

port = settings.port
smtp_server = settings.smtp_server
sender_email = settings.sender_email  # Enter your address
password =settings.sender_password
theme = "FRIM Notification"
sender =settings.sender

receiver_email = 'ainur.fadzil@redtone.com'  # Enter receiver address

message = """Hi <PegawaiName>, \r\n\
    
Pembalak request to Add Tual.
For detail, please click here <link>\r\n\

This email is automatically generated by system. Please do not reply."""
    
sender_password = password
session = smtplib.SMTP(smtp_server, port)
session.login(sender_email, sender_password)
msg = f'From: {sender}\r\nTo: {receiver_email}\r\nContent-Type: text/plain; charset="utf-8"\r\nSubject: {theme}\r\n\r\n'
msg += message
session.sendmail(sender_email, receiver_email, msg.encode('utf8'))
session.quit()